version: '3.9'

services:

  web:
    restart: always
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code # Mount the current directory as /code (hot reload)
    ports:
        - "8000:8000"
    environment:
        - SECRET_KEY=secret
        - DJANGO_SETTINGS_MODULE=config.settings.development

          # Database
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres_data: